"""initial_create_recordings

Revision ID: 05de11df7f1c
Revises: 
Create Date: 2026-02-20 14:33:54.013649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05de11df7f1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordings')
    # ### end Alembic commands ###
